#pragma once
#include "section/type.h"
#include "section/import.h"
#include "section/function.h"
#include "section/table.h"
#include "section/memory.h"
#include "section/global.h"
#include "section/export.h"
#include "section/start.h"